### ISSUE TITLE
Site Redesign Overhaul

### ISSUE THREAD

**Issue by Namchee** [ftis-admin/pinjam-ruang#4]
Hello, @chez14 

Sorry for some delay on front-end parts. I'm assigning you to this issue since you're the leader of this project and this will change our project dramatically.

**Background**

Since we began working on this project, we don't have a concrete basis for UI layout for the main page. Because of that, the current state of dashboard is really hard to manage (e.g : I'm having a hard time configuring responsiveness of the dashboard). So, I'm trying to redesign the site.

**Proposed Solution**

I've sent you (you'll know where!) my proposed design for the site. Although it's crude, I think it'll suffice for now.

Please review this issue ASAP. Thank You! 😄

**Comment by chez14** [comment]
As dicussed, please continue refining the UI/UX. You can take out the 'home' page if it has no content in idea and directly show the schedule list for all rooms (maybe like... last 30 event on any room?).

Actually the responsiveness it not a big deal since the user is mainly will use computer with at least 1366x768, but since you've set a high bar on it, let's keep it.

**Comment by chez14** [comment]
Note, i'm adding this to a Milestone to let people know our last track with this project. Feel free to describe (by opening issues) your task list and add it to the milestone.

**Comment by chez14** [comment]
I'll close this as it was resoled on last discussion. Feel free to reopen if you have more questions.
